
////
The main body of the document follows the preface, and any number of top-level clauses can be added before the annexes.
They in turn can contain any number of subclauses.

It is good practice to insert anchors before all clauses, in case you need to cross-reference them from elsewhere
in the document.

The first clause in S-100 documents is an Overview clause, and it has a fixed structure, as shown below:

* Introduction (mandatory)
* References (recommended)
*  Terms, definitions and abbreviations (mandatory)
** Use of Language (recommended)
** Terms and Definitions (mandatory)
** Abbreviations (mandatory)
*  General data product description (mandatory)
*  Data Product Specification metadata (mandatory)
*  Product Specification maintenance (mandatory)

(S-97 A-6.2.1, A-6.2.2)
////

[[sec-overview]]
== Overview
With the advent of electronic navigation and the technological progress of surveying systems and production capabilities, the ability to enhance maritime navigation with the portrayal of high resolution bathymetry has become a requirement. The provision and utilization of such data in a standardized format is essential to support the safe and precise navigation of marine vessels, and furthermore an important basis for many other maritime applications.

////
The first subclause of the Overview is an Introduction. This section gives information about the creation of the Product Specification, which includes the subject
matter and intent of the Product Specification.
////

=== Introduction
This document describes an S-100 compliant product specification for a bathymetric surface product. Incorporating aspects of the navigation surface concept <<MavigationSurface,[Smith et al, 2002]>>, an S-102 bathymetric surface product is a digital elevation model which represents the seafloor in a regular grid structure. It can be used alone or as an important element/source for future S-100 conformant ECDIS navigation. The product specification is based on the IHO S-100 framework specification and the ISO 19100 series of standards. It comprises the content model (spatial structure and metadata), encoding structure, portrayal and exchange file format for a bathymetric surface product.

////
The next subclause is a References section. Bibliographies in Metanorma Asciidoc are always given the `[references]` role attribute,
and have a fixed structure of a list of bibliographic anchors and bibliographic tags (typically standards identifiers). See
https://www.metanorma.org/author/topics/sections/bibliography/ for documentation of how Metanorma deals with bibliography.

This section should list standards which define integral elements of the Product Specification; or on which
implementations depend, such as normative ISO or other standards. Other standards or documents
containing useful information which is not an integral part of the Product Specification may be listed as
informative references, in an annex.
////

[bibliography]
=== References
* [[[iho-s100,IHO S-100]]]

* [[[iho-s44,IHO S-44]]]

* [[[iho-s4,IHO S-4]]]

* [[[iho-s32,IHO S-32]]]

* [[[iso-8601,ISO 8601:2004]]]

* [[[iso-639-2,ISO 639-2:1998]]]

* [[[iso-ts-19103,ISO/TS 19103:2015]]]

* [[[iso-19111,ISO 19111:2007]]]

* [[[iso19115,ISO 19115:2003]]]

* [[[iso-19115-1,ISO 19115-1:2014/Amd 1:2018]]]

* [[[iso-19115-2,ISO 19115-2:2009]]]

* [[[iso-19115-3,ISO/TS 19115-3:2016]]]

* [[[iso-19123,ISO 19123:2005]]]

* [[[iso-19129,ISO 19129:2009]]]

* [[[iso-19131,ISO 19131:2007/Amd 1:2011]]]

* [[[iso-iec-19501,ISO/IEC 19501:2005]]]

* [[[iso3166,ISO 3166-2:2013]]]

* [[[iso-ts-19130,ISO/TS 19130:2010]]]

* [[[iso-ts-19130-2,ISO/TS 19130-2:2014]]]

* [[[iso19139,ISO/TS 19139:2007]]]

* [[[iso-10646-1,ISO/IEC 10646-1:2000]]]


[%bibitem]
==== The Navigation Surface: A New Database Approach to Creating Multiple Products from High-Density Surveys
id:: MavigationSurface
docid::
  type::: IHO
  id::: IHO
date::
    type::: published
    value::: 2002
link::
    type::: src
    content::: http://scholars.unh.edu/ccom/976
contributor::
  role::: author
  person:::
    name::::
+
--
completename::
  language::: en
  content::: Shep M. LT Smith
--
  role::: author
  person::
    name::::
+
--
completename::
  language::: en
  content::: Lee Alexander
--
  role::: author
  person::
    name::::
+
--
completename::
  language::: en
  content::: Andy Armstrong
--

////
The next subclause are Terms, definitions, and abbreviations. 
////

=== Terms, definitions and abbreviations

////
Each terminal subclause under a terms clause in Metanorma is by default a new term. The first subclause is flagged as not a term,
`[.nonterm]`, because it is a description of the language used  in the rest of the terms clause. The following wording has been
adopted in S-100:
////

[.nonterm]
==== Use of language

Within this document:

* "`Must`" indicates a mandatory requirement.
* "`Should`" indicates an optional requirement, that is the recommended process to be followed, but is not mandatory.
* "`May`" means "`allowed to`" or "`could possibly`" and is not mandatory.

////
Terms and definitions are listed separately to abbreviations. 

Terms and definitions are useful references that reflect the content of the Specification as well as the
context for its intended use.
////

==== Terms and definitions

////
As there are no further nested clauses, the clauses under "Terms and definitions"' are each a distinct term
////

===== Coverage

*Feature* that acts as a function to return values from its range for any direct position within its spatial, temporal, or *spatiotemporal domain*.

NOTE: In other words, a coverage is a feature that has multiple values for each attribute type, where each direct position within the geometric representation of the feature has a single value for each attribute type.

[example]
Examples include a digital image, polygon overlay, or digital elevation matrix

////
Abbreviations are listed separately, as a definition list.

Any abbreviations used in the Specification should be listed with their full meaning in a separate
abbreviations section within the introductory parts of the Product Specification.
////

==== Abbreviations
This Product Specification adopts the following convention for presentation purposes:

API:: Application Programming Interface
BAG:: Bathymetric Attributed Grid
DS:: Digital Signature
DSS:: Digital Signature Scheme
ECDIS:: Electronic Chart Display Information System
ECS:: Electronic Chart System
ENC:: Electronic Navigational Chart
GML:: Geography Markup Language
IHO:: International Hydrographic Organization
ISO:: International Organization for Standardization
LIDAR:: Light Detection and Ranging
NS:: Navigation Surface
ONS:: Open Navigation Surface
PK:: Public Key
SA:: Signature Authority
SK:: Secret Key
SONAR:: Sound Navigation and Ranging
UML:: Universal Modelling Language

////
The General data product description is an informal description of the data product, formulated like an abstract.
The following illustrates a typical set of elements in a product specification:

* title
* abstract
* acronym
* content
* spatialExtent
* temporalExtent
* specificPurpose

////

=== General S-102 data product description

*Title*:: Bathymetric Surface Product Specification

*Abstract*:: This document is a Product Specification for a bathymetric surface which may be used alone or as an important element/source for future S-100 conformant ECDIS navigation. The product is defined as a data set with different coverages. This Product Specification includes a content model and separate encodings.

*Acronym*:: S-102

*Content*:: The Product Specification defines all requirements to which S-102 bathymetric data products must conform. Specifically, it defines the data product content in terms of features and attributes within the feature catalogue. The display of features is defined by the symbols and rule sets contained in the portrayal catalogue. The Data Classification and Encoding Guide (DCEG) provides guidance on how data product content must be captured. <<annex-data-classification-and-encoding-guide>>, in addition to <<annex-feature-catalogue>>, will provide implementation guidance for developers.

*Spatial Extent*::
*Description*: Areas specific to marine navigation. +
*East Bounding Longitude*: 180째 +
*West Bounding Longitude*: -180째 +
*North Bounding Latitude*: 90째 +
*South Bounding Latitude*: -90째

*Purpose*:: The primary purpose of the Bathymetric Surface Product is to provide high resolution bathymetry in gridded form in support of safety of navigation. A Bathymetric Surface Product may exist anywhere in the maritime domain. There are no limitations to its extent. Portrayal of S-102 bathymetry with other S-100 compliant products are intended to support safe passage, precise berthing and mooring, as well as route planning of marine vessels. The secondary purpose of a bathymetric surface product is to provide high resolution bathymetric data for other maritime applications.

////
Data Product Specification metadata. 
////

=== Product Specification metadata
This information uniquely identifies this Product Specification and provides information about its creation and maintenance. For further information on dataset metadata, see <<sec-metadata>>.

*Title*:: Bathymetric Surface Product Specification
*S-100 Version*:: 4.0.0
*S-102 Version*:: 2.1.0
*Date*:: October 2022

*Language*:: English
*Classification*:: Unclassified
*Contact*::
+
--
International Hydrographic Bureau +
4 Quai Antoine 1er +
B.P. 445 +
MC 98011 MONACO CEDEX +
Telephone: +377 93 10 81 00 +
Fax: +377 93 10 81 40 +
Email: mailto:info@iho.int[] +
--
*URL*:: link:http://www.iho.int/[www.iho.int]
*Identifier*:: IHO:S100:S102:2:1:0
*Maintenance*:: Changes to the Product Specification S-102 are coordinated by the IHO S-100 Working Group (S-100WG), and must be made available via the IHO web site. Maintenance of the Product Specification must conform to IHO Resolution 2/2007, as amended.

////
Product Specification Maintenance.

Changes to a Product Specification issued by the IHO will be released as a New Edition, a Revision, or as a
document that includes Clarifications. Which level is used depends on the nature of the change. It is likely
that other issuing authorities will follow IHOs example. Generally, this text follows the guidance given in S-
100 Part 12, where three types of change are described: New Edition, Revision and Clarification. 
Each is described in its own subclause, as shown below.
////
=== IHO Product Specification Maintenance

==== Introduction
Changes to S-102 will be released by the IHO as a New Edition, revision, or clarification.

==== New Edition
_New Editions_ of S-102 introduce significant changes. _New Editions_ enable new concepts, such as the ability to support new functions or applications, or the introduction of new constructs or data types. _New Editions_ are likely to have a significant impact on either existing users or future users of S-102.

==== Revisions
_Revisions_ are defined as substantive semantic changes to S-102. Typically, _revisions_ will change S-102 to correct factual errors; introduce necessary changes that have become evident as a result of practical experience or changing circumstances. A _revision_ must not be classified as a clarification. Revisions could have an impact on either existing users or future users of S-102. All cumulative _clarifications_ must be included with the release of approved _revisions_.

Changes in a revision are minor and ensure backward compatibility with the previous versions within the same Edition. Newer revisions, for example, introduce new features and attributes. Within the same Edition, a dataset of one version could always be processed with a later version of the Feature and Portrayal Catalogues.

In most cases a new feature or portrayal catalogue will result in a _revision_ of S-102.

==== Clarification
_Clarifications_ are non-substantive changes to S-102. Typically, _clarifications_: remove ambiguity; correct grammatical and spelling errors; amend or update cross references; insert improved graphics in spelling, punctuation and grammar. A _clarification_ must not cause any substantive semantic change to S-102.

Changes in a _clarification_ are minor and ensure backward compatibility with the previous versions within the same Edition. Within the same Edition, a dataset of one clarification version could always be processed with a later version of the Feature and Portrayal Catalogues, and a Portrayal Catalogue can always rely on earlier versions of the Feature Catalogue.

////
The associated version control numbering to identify changes (n) in S-100 and derived Product
Specifications generally follow this format:

*  New Editions denoted as n.0.0
*  Revisions denoted as n.n.0
*  Clarifications denoted as n.n.n

The same format for versioning has also being adopted for most of IHOs other Standards.
////

==== Version Numbers
The associated version control numbering to identify changes (n) to S-102 must be as follows:

New Editions denoted as **n**.0.0

Revisions denoted as n.**n**.0

Clarifications denoted as n.n.**n**
