////
Any S-100-based Product Specification should provide information on how data conforming to the Product
Specification is to be captured. This information should be as detailed and specific as necessary. To this
end, the S-100 Product Specification Template recommends the development of a Data Classification and
Encoding Guide (DCEG). The DCEG is used to link real world examples to the data model.

(S-97 A-6.2.15)
////

== Data Capture and Classification
The Data Classification and Encoding Guide (DCEG) describes how data describing the real world should be captured using the types defined in the S-102 Feature Catalogue. This Guide is located at <<annex-data-classification-and-encoding-guide>>.

There are a number of sounding techniques, including SONAR and LIDAR that are used to capture bathymetric data. It is permitted, but not required, to include data acquisition information in the metadata of an S-102 Bathymetric Surface product. The metadata class S102_AcquisitionMetadata has been defined, but the information elements to populate this metadata class should be identified in a national profile of S-102.
