////
TODO: This is out of sequence relative to S-97. IHO to clarify ordering

Portrayal is an optional part of a Product Specification. However, if consistent portrayal across all user
platforms is important to an S-100-based data product, then specifying how portrayal is done becomes
mandatory. Within S-100 Product Specifications, this is done by including a Portrayal Catalogue. The
Portrayal Catalogue is a collection of defined portrayal instructions for a Feature Catalogue; and includes
portrayal functions, symbols and portrayal context.

(S-97 A-6.2.20)
////

[[sec-portrayal]]
== Portrayal

=== Introduction
This clause describes the display of bathymetric surface data to support the safe navigation of marine vessels. The following portrayal options are intended to enhance mariner decision making while taking into consideration the need to minimize cluttering of the navigation display. S-102 portrayal options:

* Display of gridded bathymetry
* Colouring options to support safe navigation.


=== Generation and display of gridded bathymetry
Most modern hydrographic surveys are conducted using high-resolution multibeam sonar systems. While these systems provide a highly detailed depiction of the seafloor, the storage and processing requirements (that is, data management) can be challenging. A typical hydrographic survey can collect upwards of 10 billion depth estimates over a thirty-day collection period.

Utilization of a gridded data structure eases the data management concerns of the hydrographer, providing the ability to safely decimate the total sum of collected depth estimates into a manageable quantity of representative nodal depths for processing and production. All gridded datasets should be exposed to rigid Quality Assurance/Control procedures to ensure the final gridded dataset accurately represents the real-world environment. Once a dataset passes an established Quality Assurance/Control process, modern chart production software is used to extract candidate nodal depths from the grid for consideration as final charted soundings.

_<<annex-s102-gridding-methods>> provides a listing of S-102 accepted gridding methods._

_<<annex-gridding-full-resolution-source-bathymetry>> provides an example gridding process, discussing the difference between full resolution source bathymetry, product scale grid, and charted sounding._

==== Charted soundings/contours vs. gridded bathymetry
Depth information on a nautical chart is generally displayed as depth soundings, depth contours, and depth areas. Depth contours are used to connect soundings of equal elevation referenced to a specific sounding datum.

The introduction of a fourth depth source, S-102 gridded data, enhances navigation decision making by providing the mariner with the ability to visualize and colour a pseudo three-dimensional, sun-illuminated, contiguous image of the seafloor. While this is a benefit, producers should understand that the selection of an improper grid resolution (that is too coarse, or too fine) may complicate the overall navigation solution when displayed with traditional depth information. <<tab-informative-grid-resolution-and-resulting-tile-size-at-chart-scale>> provides informative grid resolutions for each charting scale to aid in the selection of a final grid resolution. It should be noted that <<tab-informative-grid-resolution-and-resulting-tile-size-at-chart-scale>> does not contain mandatory resolutions. Final identification of the "`appropriate`" resolution is left to the data producer.

