////
Metadata is data about data. In S-100 the primary purpose of metadata is to provide information about
the identification; spatial and temporal extent; quality; application schema; spatial reference system; and
distribution of digital geographic data. Metadata is applicable to the cataloguing of datasets; clearinghouse
activities; and the full description of geographic and non-geographic resources.

(S-97 A-6.2.19)

////

[[sec-metadata]]
== Metadata

=== Introduction
The Metadata elements used in the Bathymetric Surface product are derived from S-100 and from <<iso19115>> and <<iso-19115-2>>. Optionally additional metadata may be derived from <<iso-ts-19130>> and <<iso-ts-19130-2>> especially metadata relating to the SONAR equipment which may have been used to acquire the bathymetric data.

There are only a few elements in the <<iso19115>> metadata standard that are mandatory and these relate only to the use of the metadata for identification and pedigree of the data set. A minimum level of data identification is required for all applications including database applications, web services and data set production. However, S-102 requires certain metadata attributes which are used to geolocate the dataset as well as establish a pedigree for the data.

The elements are related in a metadata Schema and include definitions and extension procedures. There exist both mandatory and conditional metadata elements. Only a few metadata elements are mandatory but the inclusion of some of the optional metadata elements establish a situation where other metadata elements are conditionally made mandatory.

<<tab-s102-handling-of-core-metadata-elements>> outlines the core metadata elements (mandatory and recommended optional) required for describing a geographic information data set. The codes indicate: "M" mandatory, "O" optional' "C" conditional as defined in <<iso19115>>. <<tab-s102-handling-of-core-metadata-elements>> indicates how the mandatory, optional and conditional core metadata are handled in S-102.

[[tab-s102-handling-of-core-metadata-elements]]
.S-102 Handling of Core Metadata Elements
[cols="a,a"]
|===

|*Dataset title (M)*

S102_DS_DiscoveryMetadata > citation > CI_Citation.title

from: (MD_Metadata.identificationInfo > MD_DataIdentification.citation > CI_Citation.title)

|*Spatial representation type (O)*

S102_DS_DiscoveryMetadata > spatialRepresentationType: MD_ DataIdentification. spatialRepresentationType

002 -- Grid; (for regular grid coverage)

from: (MD_Metadata.identificationInfo > MD_DataIdentification.spatialRepresentationType)

|*Dataset reference date (M)*

S102_DS_DiscoveryMetadata > citation > CI_Citation.date

from: (MD_Metadata.identificationInfo > MD_DataIdentification.citation > CI_Citation.date)

|*Reference system (O)*

S102_StructureMetadataBlock > hRefSystem +
and +
S102_StructureMetadataBlock > vRefSystem

from: (MD_Metadata.referenceSystemInfo > MD_ReferenceSystem.referenceSystemIdentifier > RS_Identifier)

|*Resource point of contact (O)*

S102_DS_DiscoveryMetadata > pointOfContact > CI_Responsiblity

from: (MD_Metadata.identificationInfo > MD_DataIdentification.pointOfContact > CI_Responsiblity)

|*Lineage (O)*

S102_QualityMetadataBlock > S102_LI_Source +
and +
S102_QualityMetadataBlock > S102_LI_ProcessStep

from: (MD_Metadata.resourceLineage > > LI_Lineage)

|*Geographic location of the dataset (by four coordinates or by geographic identifier) \(C)*

S102_DS_DiscoveryMetadata > extent > EX_Extent

from: (MD_Metadata.identificationInfo > MD_identification.extent > EX_Extent > EX_GeographicBoundingBox +
or +
EX_GeographicDescription)

|*On-line link to resource (O)*

(MD_Metadata.distributionInfo > MD_Distribution > MD_DigitalTransferOption.onLine > CI_OnlineResource)

Optional - not required

|*Dataset language (M)*

S102_DS_DiscoveryMetadata > language

from: (MD_Metadata.identificationInfo > MD_DataIdentification.language)

|*Metadata file parent identifier \(C)*

(MD_Metadata.parentMetadata > CI_Citation.identifier)

Implicit in S-102 product specification reference to
<<iso-19115-1>> as a normative reference

|*Dataset character set \(C)*

set to default = "utf8". [not required when set to default from <<iso19115>>]

from: (MD_Metadata.identificationInfo > MD_DataIdentification.defaultLocale > PT_Locale.characterEncoding)

|*Metadata standard name (O)*

(MD_Metadata.metadataStandard > CI_Citation.title)

Implicit in S-102 product specification reference to <<iso-19115-1>> as a normative reference

|*Dataset topic category (M)*

S102_DS_DiscoveryMetadata > topicCategory:

MD_TopicCategoryCode +
006 -- elevation; +
014 -- oceans; +
012 -- inlandWaters

Frome: (MD_Metadata.identificationInfo > MD_Identification.topicCategory)

|*Metadata standard version (O)*

(MD_Metadata.metadataStandardVersion) +
Implicit in S-102 product specification reference to <<iso-19115-1>> as a normative reference

|*Spatial resolution of the dataset (O)*

(MD_Metadata.identificationInfo > MD_DataIdentification.spatialResolution > MD_Resolution.equivalentScale +
or +
MD_Resolution.distance) +
Since this data set is a grid coverage resolution is defined by the coverage grid parameters

|*Metadata language \(C)*

(MD_Metadata. defaultLocale > PT_Locale.language)

The language is set to English. In addition, additional languages may be used in accordance with the structure for handling multi-languages per <<iso-19115-1>>

|*Abstract describing the dataset (M)*

S102_DS_DiscoveryMetadata > abstract

from: (MD_Metadata.identificationInfo > MD_DataIdentification.abstract)

|*Metadata character set \(C)*

set to default = "utf8". [not required when set to default from <<iso-19115-1>>]

from: (MD_Metadata. defaultLocale > PT_Locale.characterEncoding)

|*Distribution format (O)*

(MD_Metadata.distributionInfo > MD_Distribution > MD_Format)

Optional - not applicable

To maintain the separation of carrier and content the content model does not contain any format information. This would be included in a transmittal or by file types.

|*Party responsible for the metadata information (M)*

S102_DS_DiscoveryMetadata > contact

from: (MD_Metadata.contact > CI_Responsibility.CI_Individual +
or +
MD_Metadata.contact > CI_Responsibility.CI_Organisation)

|*Temporal extent information for the dataset (O)*

(MD_Metadata.identificationInfo > MD_Identification.extent > EX_Extent.temporalElement

|*Date(s) associated with the metadata (M)*

S102_DS_DiscoveryMetadata > dateInfo

from: (MD_Metadata.dateInfo > CI_Date)

|*Vertical extent information for the dataset (O)*

MD_Metadata.identificationInfo > MD_DataIdentification.extent > EX_Extent.verticalElement > EX_VerticalExtent

|*Name of the scope/type of resource for which the metadata is provided (M)*

S102_DS_DiscoveryMetadata > resourceScope

from: (MD_Metadata.metadataScope > MD_MetadataScope.resourceScope > MD_ScopeCode (codelist -- <<iso-19115-1>>))

|===

The dataset metadata is stored in a separate file encoded according to the ISO 19115X Schemas. The name of the metadata file is MD_<HDF5 data file base name>.XML (or .xml) ISO metadata (per <<iho-s100,part=10c,clause=10c-12>>), The root element in the file is *S102_DSMetadataBlock* which contains *S102_DS_DiscoveryMetadata*, *S102_StructureMetadataBlock* and *S102_QualityMetadataBlock*. 

[[subsec-discovery-metadata]]
=== Discovery metadata
Metadata is used for a number of purposes. One high level purpose is for the identification and discovery of data. Every data set needs to be identified so that it can be distinguished from other data sets and so it can be found in a data catalogue, such as a Web Catalogue Service. The discovery metadata applies at the *S102_DataSet* level. Metadata in *S102_DiscoveryMetadataBlock* is encoded in a separate metadata file within the *S102_DSMetadataBlock*.

...

